---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/awx-ee:23.5.0
  #EE_BUILDER_IMAGE: quay.io/ansible/ansible-builder:lastet
dependencies:
  #galaxy: requirements.yml
  python: requirements.txt
  #system: bindep.txt
additional_build_steps:
  append: |
    RUN pip3 install --upgrade pip setuptools
