---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/omarelhaoudar/awx-ee:custom-update2
additional_build_steps:
  prepend:
    - RUN rm -rf $(find / -name *ansible*)
  append:
    - RUN \
         dnf install python36 -y && \
         dnf install python3-virtualenv -y && \
         virtualenv-3.6 -p python3.6 venv && \
         source venv/bin/activate
    - RUN echo "export PATH=/runner/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc 
    - RUN pip3 install ansible==2.9.11


    #- RUN alias python3=python3.6
    #- RUN export python3=python3.6