---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/ansible-runner:devel
additional_build_steps:
  prepend:
    - RUN rm -rf /usr/local/share/ansible-runner
    - RUN rm -rf /usr/local/bin/ansible*
    - RUN rm -rf /usr/local/lib/python3.8/site-packages/ansible*
    - RUN rm -rf /home/runner/.ansible
    - RUN dnf install python36 -y
  append:
    - RUN unlink /usr/bin/python3
    - RUN ln -s /usr/libexec/platform-python3.6 /usr/bin/python3
    - RUN pip3 install --upgrade pip setuptools
    - RUN pip install ansible==2.9.11